services:
  traefik:
    image: traefik:v3.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # create traefik.yaml file inside config folder
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
    networks:
      - traefik_proxy
    restart: unless-stopped
networks:
  #The network should be created before running the container
  traefik_proxy:
    external: true
