services:
  traefik:
    image: traefik:v3.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      # Do not expose 8080 on production
      - "8080:8080"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # create traefik.yaml file inside config folder
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      # create directory data/certs  
      - ./data/certs/:/var/traefik/certs/:rw
    networks:
      - traefik_proxy
    restart: unless-stopped
networks:
  #The network should be created before running the container
  traefik_proxy:
    external: true
