global:
  checkNewVersion: false
  sendAnonymousUsage: false
log: 
  # For testing propose use level debug, change this in production
  # to no not having to much noising
  level: DEBUG
api:
  dashboard: true
  insecure: true
entrypoints:
  web: 
    address: 80
    # This redirections should only be used after config tls & https cert resolvers
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: 443
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
certificatesResolvers:
  cloudflare:
    acme:
      email: your_cloudflare_email@email.com
      storage: /var/traefik/certs/cloudflare-acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        #delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted 
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
